"""
Django settings for statuspage project.

Generated by 'django-admin startproject' using Django 1.11.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))




# Hardcoded Part

BASE_URL = "http://9dd96382.ngrok.io"
STATUSPAGE_ACCESS_TOKEN = "11649b9b-ea84-47fa-aecb-9faf3ab447bd"
PAGE_ID = "gvl671ncn9wm"
ORGANIZATION_ID = "zs0dhxtjvt6g"

# End of Hardcoded Part



### Statuspage specific settings ###

END = ".json"
SP_API_BASE1 = "https://api.statuspage.io/v1/pages/"
SP_API_BASE2 = "https://api.statuspage.io/v0/organizations/"
USER_PROFILE_ENDPOINT = PAGE_ID + END
USER_COMPONENTS_ENDPOINT = PAGE_ID + "/components" + END
USER_ALL_INCIDENTS_ENDPOINT =  PAGE_ID + "/incidents" + END
USER_UNRESOLVED_ENDPOINT = PAGE_ID + "/incidents/unresolved" + END
CREATE_INCIDENT = PAGE_ID + "/incidents" + END

### End of Statuspage specific settings ###





### YellowAnt specific settings ###

# URL to obtain oauth2 access for a YA user
YELLOWANT_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"

# URL to receive oauth2 codes from YA for user authentication. As a developer, you need to provide this URL in the YA
# developer console so that YA knows exactly where to send the oauth2 codes.
YELLOWANT_REDIRECT_URL = "http://c3a5851f.ngrok.io/yellowantredirecturl/"

# Numerical ID generated when you register your application through the YA developer console
YA_APP_ID = "343"

# Client ID generated from the YA developer console. Required to identify requests from this application to YA
YELLOWANT_CLIENT_ID = "EyJ51G3GGMroQjd6VtVBmz2cCGVitL9S93wnNHCe"

# Client secret generated from the YA developer console. Required to identify requests from this application to YA
YELLOWANT_CLIENT_SECRET = "8AsfOHpfs5oIsTYR9Ibbcvb2Zv3z3a1uRfrg5vaaYFMEcAGD8VbhORy0GdTRTfTW0uDHh0DjvOv3yHWhYKKmQckxGTJ0IOn2XPdmKjyu3Uf400tk7k6VbozmNDig9p3A"

# Verification token generated from the YA developer console. This application can verify requests from YA as they will
# carry the verification token
YELLOWANT_VERIFICATION_TOKEN = "7flQD3YMVQoSXBwIfIpaEFRUwY0FBMVv6FJcmTmSWopDBkTc2mhyaKShiTuOKDlGR553Q2GRmbOD98eN82whb0ao8aUtyaCbGrcds5CUSQS0zeyccCPtxrT8i7n2DcAO"

### END YellowAnt specific settings ###


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x(x(&j#%$a9jmh7bmw*4f59hdmyn7uih)+0zd2rwib7o$0!+7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'web.apps.WebConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'records'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'statuspage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'statuspage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'statusdb',
        'USER': 'root',
        'PASSWORD': 'vimal_1996',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
