# Generated by Django 2.0.5 on 2018-05-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180516_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspageusertoken',
            name='statuspage_page',
            field=models.CharField(default='', max_length=25),
        ),
    ]
