# Generated by Django 2.0.5 on 2018-06-11 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20180529_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspageusertoken',
            name='webhook_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='statuspageusertoken',
            name='webhook_last_updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
