# Generated by Django 2.0.5 on 2018-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_pagedetail_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yellowusertoken',
            name='user',
            field=models.IntegerField(),
        ),
    ]
